# Generated by Django 3.1.3 on 2021-01-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_conversation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='conversation_id',
            new_name='conversation',
        ),
    ]
