# Generated by Django 3.1.3 on 2021-02-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210121_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
